management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
  #      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "env,beans"

info:
  app:
    name: hello-actuator
    company: bell

logging:
  level:
    hello.controller: debug
